@startuml CL_Preview
' requirement REQ-00004-1
' requirement REQ-00007-1

!startsub PreviewModule

namespace client.preview {
  class registerPreview <<function>> {
    + registerPreview(context: ExtensionContext) : void
  }
}

!endsub

@enduml
