@startuml CL_ServerOptions
' requirement REQ-00002-1

!startsub ServerOptionsModule

namespace client.serverOptions {
  class resolveServerCommand <<function>> {
    + resolveServerCommand(configuredPath: string | undefined) : string
  }
  class documentSelector <<function>> {
    + documentSelector() : { scheme: string; language: string }[]
  }
}

!endsub

@enduml
