@startuml CL_PlantumlVscode
' requirement REQ-00001-1
' requirement REQ-00002-1
' requirement REQ-00003-1

!startsub ServerOptions
!includesub ./CL_ServerOptions.puml!ServerOptions
!endsub

!startsub Extension
!includesub ./CL_Extension.puml!Extension
!endsub

@enduml
