@startuml CL_WebviewPreview
' requirement REQ-00004-1
' requirement REQ-00005-1

!startsub WebviewPreviewModule

namespace webview.preview {
  class init <<function>> {
    + init() : Promise<void>
  }
  class rerender <<function>> {
    + rerender() : void
  }
}

!endsub

@enduml
